### ISSUE TITLE
Aqua CLI options

### ISSUE THREAD

**Issue by zuZuz** [Naranbataar/Aqua#1]
Hello, @Naranbataar! 

Thanks for your program, it works fine. But I can't understand cli options:

```
-c message size, defaults to 245, or (255 - s) if -s provided
-s number of symbols, defaults to 10, or (255 - c) if -c provided  
```

Could you explain their purpose, please?

**Comment by Naranbataar** [comment]
Hello! Sure, it works like that:

The data is chunked on chunks of 2-255 bytes

Message size: how many bytes of the chunk will be used for data
Number of symbols: how many bytes of the chunk will be used for ECC symbols

If no option is provided, the chunk will be 255 bytes, 245 bytes of data, with 10 symbols
If one option is provided, the chunk will be 255 bytes, and the rest will be used for the option that you not provided
If two options are provided, the chunk will be the message size, plus the number of symbols

For example: 
- `-s 20`  20 bytes for symbols and 235 bytes for data (255 bytes)
- `-c 230` 230 bytes for data and 25 bytes for symbols (255 bytes)
- `-s 10 -c 100`  10 bytes for symbols and 100 bytes for data (110 bytes)

The same options are required for encoding and decoding
